# Generated by Django 4.1 on 2022-10-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_record_course_alter_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
