# Generated by Django 4.1 on 2022-10-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_coursestudent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursestudent',
            old_name='course',
            new_name='course_1',
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='course_2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='course_d1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='course_d2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='course_o1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='course_o2',
            field=models.CharField(default='', max_length=20),
        ),
    ]
